//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticsFactory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInput
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MSDH { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> Own { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual ProductInput ProductInput { get; set; }
    }
}
